version: '3.8'

services:
  client-frontend:
    image: frontend:0.0.1
    build: frontend
    restart: always
    ports:
      - '3000:5173'
    env_file:
      - frontend/.env.docker
    depends_on:
      - user-service
    volumes:
      - /app/node_modules
      - ./frontend:/app

  user-service:
    image: user-service:0.0.1
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      - service-db
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      - SERVER_PORT=8181
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db/user_service_db
      - FOLDER_ID=${FOLDER_ID}
      - BUCKET_MINIO=${BUCKET_MINIO}
      - MINIO_USER=${MINIO_USER}
      - MINIO_PASSWORD=${MINIO_PASSWORD}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-1:9092,kafka-2:9094,kafka-3:9096
      - YANDEX_SPEECH_API_KEY=${YANDEX_SPEECH_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - FFMPEG_PATH=/usr/bin/ffmpeg
      - FFPROBE_PATH=/usr/bin/ffprobe
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - maven-repo:/root/.m2/repository
      - ./uploads:/app/uploads
      - ./subtitles:/app/subtitles

  video-service:
    image: video-service:0.0.1
    build:
      context: .
      dockerfile: video-service/Dockerfile
    ports:
      - "8182:8182"
    depends_on:
      - service-db
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      - SERVER_PORT=8182
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db/video_service_db
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-1:9092,kafka-2:9094,kafka-3:9096
      - BUCKET_NAME=${BUCKET_NAME}
      - YANDEX_SECRET_KEY_ID=${YANDEX_SECRET_KEY_ID}
      - YANDEX_SECRET_KEY=${YANDEX_SECRET_KEY}
      - YANDEX_SPEECH_API_KEY=${YANDEX_SPEECH_API_KEY}
      - FOLDER_ID=${FOLDER_ID}
      - FFMPEG_PATH=/usr/bin/ffmpeg
      - FFPROBE_PATH=/usr/bin/ffprobe
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - maven-repo:/root/.m2/repository
      - ./uploads:/app/uploads
      - ./subtitles:/app/subtitles

  service-db:
    image: postgres:14.7-alpine
    environment:
        POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
        POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
        - "15432:5432"
    volumes:
        - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
        - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
   container_name: pgadmin4_container
   image: dpage/pgadmin4:9.8
   restart: always
   environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
   ports:
     - "5050:80"
   volumes:
     - pgadmin-data:/var/lib/pgadmin

  kafka-1:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=XvbQ83CcTHCoEOpIvzNSKg
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9090,EXTERNAL://kafka-1:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - ./volumes/server-1:/bitnami/kafka

  kafka-2:
    image: bitnami/kafka:latest
    ports:
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_KRAFT_CLUSTER_ID=XvbQ83CcTHCoEOpIvzNSKg
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9090,EXTERNAL://kafka-2:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - ./volumes/server-2:/bitnami/kafka

  kafka-3:
    image: bitnami/kafka:latest
    ports:
      - "9096:9096"
    environment:
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_KRAFT_CLUSTER_ID=XvbQ83CcTHCoEOpIvzNSKg
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9096
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-3:9090,EXTERNAL://kafka-3:9096
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - ./volumes/server-3:/bitnami/kafka

volumes:
  db-data:
  pgadmin-data:
  ffmpeg-bin:
  maven-repo: