version: '3.7'
services:
  minio:
    container_name: minio
    image: bitnami/minio:2024.12.18
    restart: always
    ports:
      - '9900:9000'
      - '9901:9001'
    volumes:
      - 'minio_data:/bitnami/minio/data'
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=${BUCKET_MINIO}
    networks:
      internal:
networks:
  internal:


volumes:
  minio_data:
    driver: local